[package]
name = "http_contract"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/dbofmmbt/http_contract"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
http = "0.2.9"
serde = "1.0.183"
